/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "GPIO_driver.h"

int main(void)
{

	volatile GPIO_Handle Handle;
	Handle.GPIOx=GPIOD;
	Handle.Config.GPIO_PinNumber=12;
	Handle.Config.GPIO_Mode=GPIO_MODE_OUTPUT;
	Handle.Config.GPIO_OutputSpeed=GPIO_OSPEED_MED;
	Handle.Config.GPIO_OutputType=GPIO_OTYPE_PP;
	Handle.Config.GPIO_PUPD=GPIO_PUPD_NO_PUPD;
	GPIO_PeriClockControl((GPIO_Regs*)(Handle.GPIOx), ENABLE);
	GPIO_Init((GPIO_Handle*)&Handle);
	WriteToOutputPin((GPIO_Regs*)(Handle.GPIOx),12,GPIO_PIN_SET);
	for(int i=0; i<=250000;i++);
	GPIO_DeInit(GPIOD);
	GPIO_PeriClockControl((GPIO_Regs*)(Handle.GPIOx), ENABLE);
	GPIO_Init((GPIO_Handle*)&Handle);
	WriteToOutputPin((GPIO_Regs*)(Handle.GPIOx),12,GPIO_PIN_SET);
	for(int i=0; i<=250000;i++);
	GPIO_DeInit(GPIOD);
	for(;;);
}
